sonar.projectKey=minattinho_unit-test-jest
sonar.organization=minattinho
sonar.projectName=unit-test-jest
sonar.projectVersion=1.0
sonar.sources=./src
sonar.tests=./test
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=coverage/**,node_modules/**
sonar.coverage.exclusions=test/**
